INSERT INTO album_covers (artist, album, filepath, date_released, date_added) VALUES
('Van Halen', '1984', '/img/album_covers/1984.jpg', NULL, NOW()),
('Queen', 'A Night at the Opera', '/img/album_covers/a-night-at-the-opera-queen.jpg', NULL, NOW()),
('The Beatles', 'Abbey Road', '/img/album_covers/abbey%20road.jpg', NULL, NOW()),
('Bad Company', '', '/img/album_covers/bad%20company.jpg', NULL, NOW()),
('Billy Joel', 'The Stranger', '/img/album_covers/billy joel the stranger.jpg', NULL, NOW()),
('Bob Dylan', 'Blood on the Tracks', '/img/album_covers/BloodTracksCover.jpg', NULL, NOW()),
('Bob Dylan', 'Desire', '/img/album_covers/bob%20dylan%20desire.jpg', NULL, NOW()),
('Bob Seger', 'Against the Wind', '/img/album_covers/bob%20seger%20against%20the wind.jpg', NULL, NOW()),
('Bonnie Raitt', 'Nick of Time', '/img/album_covers/Bonnie-Raitt-Nick-Of-Time.jpg', NULL, NOW()),
('Bruce Springsteen', 'Born in the USA', '/img/album_covers/Born_In_The_Usa.jpg', NULL, NOW()),
('Bruce Springsteen', 'Born to Run', '/img/album_covers/borntorun.jpg', NULL, NOW()),
('Dire Straits', 'Brothers in Arms', '/img/album_covers/brothers in arms.jpg', NULL, NOW()),
('Bad Company', 'Burnin\' Sky', '/img/album_covers/burnin sky bad company.jpg', NULL, NOW()),
('Bruce Springsteen', 'Darkness on the Edge of Town', '/img/album_covers/darkness.jpg', NULL, NOW()),
('Van Halen', 'Diver Down', '/img/album_covers/Diver%20Down.jpg', NULL, NOW()),
('Elton John', 'Goodbye Yellow Brick Rode', '/img/album_covers/Elton_John_Goodbye_Yellow_Brick_Road.jpg', NULL, NOW()),
('Fire and Water', 'Free', '/img/album_covers/free fire and water.jpg', NULL, NOW()),
('Grand Home', 'Closer to Home', '/img/album_covers/grand funk closer to home.jpg', NULL, NOW()),
('Bruce Springsteen & The E Street Band', 'Hammersmith-Odeon-London-75', '/img/album_covers/Hammersmith-Odeon-London-75.jpg', NULL, NOW()),
('', '', '/img/album_covers/Joe_Jackson_-_Night_And_Day.jpg', NULL, NOW()),
('', '', '/img/album_covers/LedZeppelin4.jpg', NULL, NOW()),
('', '', '/img/album_covers/lonesome jubilee.jpg', NULL, NOW()),
('', '', '/img/album_covers/making_movies.jpg', NULL, NOW()),
('', '', '/img/album_covers/raisingsand.jpg', NULL, NOW()),
('', '', '/img/album_covers/red-octopus.jpg', NULL, NOW()),
('', '', '/img/album_covers/rubber-soul.jpg', NULL, NOW()),
('', '', '/img/album_covers/rumours.jpg', NULL, NOW()),
('', '', '/img/album_covers/santana-abraxas.jpg', NULL, NOW()),
('', '', '/img/album_covers/santana-supernatural.jpg', NULL, NOW()),
('', '', '/img/album_covers/sittin in.jpg', NULL, NOW()),
('', '', '/img/album_covers/so peter gabriel.jpg', NULL, NOW()),
('', '', '/img/album_covers/srv.jpg', NULL, NOW()),
('', '', '/img/album_covers/steely-dan-cant-buy-a-thrill.jpg', NULL, NOW()),
('', '', '/img/album_covers/stevie-wonder-songs-in-the-key-of-life.jpg', NULL, NOW()),
('', '', '/img/album_covers/the river.jpg', NULL, NOW()),
('', '', '/img/album_covers/tommy.jpg', NULL, NOW()),
('', '', '/img/album_covers/toto 4.jpg', NULL, NOW()),
('', '', '/img/album_covers/vanhalen-5150-cover.jpg', NULL, NOW()),
('', '', '/img/album_covers/vaughan-stevie-ray-double-trouble-933-l.jpg', NULL, NOW()),
('', '', '/img/album_covers/vivid.jpg', NULL, NOW()),
('', '', '/img/album_covers/whos_next.jpg', NULL, NOW());