INSERT INTO shows (id, name, date) VALUES (1, 'June 4', '2012-06-04');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Keep on Chooglin’ (The Long Road Home, 2005)", "John Fogerty", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Gone Gone Gone (Hard Rock Live)", "Bad Company", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Seagull (Hard Rock Live)", "Bad Company", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Digging in the Dirt (Secret World Live)", "Peter Gabriel", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Future Love Paradise (Live in Paris)", "Seal", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Invisible Touch (Invisible Touch Tour, 1986-87)", "Genesis", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "I Don’t Need No Doctor (Live at the Fillmore, 1971) ", "Humble Pie", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Friday Night (2005) ", "The Darkness", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Love is Only A Feeling (Scotland, 2004)", "The Darkness", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Slap Leather (James Taylor Live)", "James Taylor", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (1, "Shower The People (James Taylor Live)", "James Taylor", NOW());
INSERT INTO shows (id, name, date) VALUES (2, 'May 21', '2012-05-21');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "Detroit Rock City (Alive IV)", "Kiss  w/ The Melbourne Symphony Orchestra", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "Rude Mood/Hide Away (1982)", "Stevie Ray Vaughan &amp; Double Trouble", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "The Sweater Song (1994)", "Weezer", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "Nothing is Easy (1991)", "Jethro Tull", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "You’ll Accomp’ny Me (Nine Tonight)", "Bob Seger &amp; The Silver Bullet Band", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "I Need a Lover (John Mellencamp cover, 1979)", "Pat Benatar", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "Rolling Stone (Now &amp; Live, 1997)", "Paul Rodgers", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "Jungleland (Hammersmith Odeon, London 1975)", "Bruce Springsteen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "Small Change (Rockpalast, 1977)", "Tom Waits", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "Purple Rain (Solo)", "Martin Sexton", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (2, "Go All The Way (Mike Douglas Show 1974)", "The Raspberries", NOW());
INSERT INTO shows (id, name, date) VALUES (3, 'May 14', '2012-05-14');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (3, "More Than Love (Live at the Fillmore, 2004)", "Los Lonely Boys", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (3, "Nobody Else (Live at the Fillmore, 2004)", "Los Lonely Boys", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (3, "Dave Matthews Band (Concert in Central Park, 2003)", "So Much To Say/Too Much", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (3, "Vienna (1993)", "Billy Joel", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (3, "Honey Creeper (The Honest Hour, 2004)", "Assembly of Dust", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (3, "Suavecito (1974)", "Malo", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (3, "Do You Feel Like We Do (Comes Alive)", "Peter Frampton", NOW());
INSERT INTO shows (id, name, date) VALUES (4, 'April 30', '2012-04-30');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (4, "The Power of Love (1985)", "Huey Lewis &amp; The News", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (4, "Dancing in the Moonlight (2006)", "Orleans", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (4, "Infected (Live on Letterman, 1994)", "Bad Religion", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (4, "Taxi (Greatest Stories Live)", "Harry Chapin", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (4, "I Can’t Change (Recorded live in studio at WVBR)", "Blow!", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (4, "I Want A New Drug", "Huey Lewis &amp; The News", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (4, "Sorrow (Acoustic live)", "Greg Graffin", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (4, "30,000 Pounds of Bananas (Greatest Stories Live)", "Harry Chapin", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (4, "Leaving on a Jet Plane (Live in Japan, 1990)", "Peter, Paul &amp; Mary", NOW());
INSERT INTO shows (id, name, date) VALUES (5, 'April 23', '2012-04-23');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "Why I Sing The Blues (Live in Africa, 1974)", "B.B. King", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "I Just Wanna Make Love To You (Live in San Francisco)", "Etta James", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "Turn the Page (Live Bullet)", "Bob Seger &amp; The Silver Bullet Band", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "Fire Lake (Nine Tonight)", "Bob Seger &amp; The Silver Bullet Band", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "Man of Constant Sorrow (2002)", "Alison Krauss &amp; Union Station", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "For The Summer (Live on Letterman)", "Ray LaMontagne", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "Little Seeker (Live Vol. 2)", "Entrain", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "Lines On My Face (Live in Detroit)", "Peter Frampton", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "Samba Pa Ti (Live in Mexico)", "Santana", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (5, "Are You Gonna Go My Way (Unplugged Collection)", "Lenny Kravitz", NOW());
INSERT INTO shows (id, name, date) VALUES (6, 'April 16', '2012-04-16');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (6, "Bat Out of Hell (Bonus track off of original album)", "Meat Loaf", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (6, "Rosalie (1974)", "Bob Seger", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (6, "Celluloid Heroes (1979)", "The Kinks", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (6, "Something (Live in Japan)", "George Harrison", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (6, "People Got To Be Free (1969)", "The Rascals", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (6, "Cold Blue Steel and Sweet Fire (Miles of Aisles)", "Joni Mitchell", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (6, "In This Life (Live from the American Ballroom)", "Donna the Buffalo", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (6, "You Took The Words Right Out of My Mouth (Hot Summer Nights live album)", "Meat Loaf", NOW());
INSERT INTO shows (id, name, date) VALUES (7, 'April 9', '2012-04-09');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "Rain on the Scarecrow (FarmAid 2008, Milwaukee)", "John Mellencamp", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "Death Don’t Have No Mercy (1970 recording, Written by Reverend Guy Davis)", "Hot Tuna", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "Lookin’ Back (Live Bullet album, 1976)", "Bob Seger &amp; The Silver Bullet Band", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "Hard Times (Solo album)", "Martin Sexton", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "Walk of Life (On The Night LIVE)", "Dire Straits", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "Let’s Call It Quits (Supersonic 1976)", "Slade", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "Tighter (KEXP-FM’s VIP Club Concert Series, Seattle, November 9, 2010)", "Fitz &amp; The Tantrums", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "Fountain of Sorrow (Solo Acoustic, Vol. 1)", "Jackson Browne", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "The River (Madison Square Garden, NYC 2002)", "Bruce Springsteen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (7, "Independence Day (Live 1975-1985, compilation album)", "Bruce Springsteen", NOW());
INSERT INTO shows (id, name, date) VALUES (8, 'April 2', '2012-04-02');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "Bring it on Home (How The West Was Won)", "Led Zeppelin", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "Maggie’s Farm (Rolling Thunder Tour 1976)", "Bob Dylan", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "Not So Sweet Martha Lorraine (Monterey Pop Festival 1967)", "Country Joe &amp; The Fish", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "Flying Higher (Woodstock Festival 1969)", "Country Joe &amp; The Fish", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "Lives in the Balance (Solo Acoustic, Vol. 1)", "Jackson Browne", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "You’re the Voice (1991)", "Heart", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "The Shock of the Lightning (Live at Wembley 2008)", "Oasis", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "Self-Esteem", "The Offspring", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "Human Wheels (Human Wheels Special 1993)", "John Mellencamp", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (8, "Under the Boardwalk", "John Mellencamp", NOW());
INSERT INTO shows (id, name, date) VALUES (9, 'March 26', '2012-03-26');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "Foxy Lady (The Hendrix Set EP)", "Paul Rodgers &amp; Company", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "Shine (Woodstock ’94)", "Collective Soul", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "December (Live in Morocco)", "Collective Soul", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "In the Sun", "Joseph Arthur", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "Rooster (Unplugged)", "Alice in Chains", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "House on the Hill (Entrain Live, Volume 2)", "Entrain", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "In Memory of Elizabeth Reed (Dreams album boxset)", "Allman Brothers", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "Melissa (Acoustic)", "Allman Brothers", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "Something (Live in Japan)", "George Harrison", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (9, "La Bamba (Live at the Fillmore)", "Los Lonely Boys", NOW());
INSERT INTO shows (id, name, date) VALUES (10, 'March 19', '2012-03-19');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (10, "Wild Women Don’t Get The Blues (Live in Texas album)", "Lyle Lovett", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (10, "Darkness on the Edge of Town (Live 1975-1985 album)", "Bruce Springsteen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (10, "Jungleland (Live in New York City album)", "Bruce Springsteen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (10, "Ready For Love (Hard Rock Live album)", "Bad Company", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (10, "Shaking the Tree (Secret World)", "Peter Gabriel", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (10, "Every Single Soul (Live at the Baobab)", "Michael Franti", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (10, "Love’s Divine (Live in Paris)", "Seal", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (10, "Can’t Let Go (Live: Volume 2)", "Entrain", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (10, "My Baby Loves a Bunch of Authors", "Moxy Fruvous", NOW());
INSERT INTO shows (id, name, date) VALUES (11, 'March 12', '2012-03-12');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (11, "Love Me Like A Man", "Bonnie Raitt", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (11, "Jody Girl (from Live Bullet)", "Bob Seger", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (11, "316/Eruption (from Right Here, Right Now album, 1993)", "Van Halen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (11, "You Really Got Me/Cabo Wabo (from Right Here, Right Now album, 1993)", "Van Halen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (11, "Pressure Drop (Live at Red Rocks)", "Toots &amp; The Maytals", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (11, "Brighton Rock Solo (Live at Wembley ’86 album)", "Queen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (11, "Hammer To Fall (Live at Wembley ’86 album)", "Queen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (11, "Open Arms (Houston, 1981)", "Journey", NOW());
INSERT INTO shows (id, name, date) VALUES (12, 'March 5', '2012-03-05');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Romeo &amp; Juliet (from On The Night)", "Dire Straits", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Come Rain or Shine (The Unplugged Collection)", "Don Henley", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Silly Boy", "The Blue Van", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Don’t Let The Sun Go Down On Me (The Unplugged Collection)", "Elton John", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Blind Love", "B.B. King", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Steal My Kisses (Berlin, Germany, May 22, 2003)", "Ben Harper &amp; The Innocent Criminals", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Nothing from Nothing (Budokan, Japan)", "Ringo &amp; His All-Starr Band Feat. Billy Preston", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Will It Go Round In Circles (from Solo album)", "Martin Sexton", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "This Little Light of Mine (Live From Dublin w/ the Seeger Sessions Band)", "Bruce Springsteen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Pickin’ Up The Pieces (KEXP’s VIP Club Concert Series, November 9, 2010)", "Fitz &amp; the Tantrums", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (12, "Tighter (KEXP’s VIP Club Concert Series, November 9, 2010)", "Fitz &amp; the Tantrums", NOW());
INSERT INTO shows (id, name, date) VALUES (13, 'February 27', '2012-02-27');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (13, "Playing in the Band (Dick's Picks Vol. 31 - Philadelphia CIvic Center)", "Grateful Dead", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (13, "Bathtub Gin (Madison Square Garden, New York, December 28, 2011)", "Phish", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (13, "Whole Lotta Love (How The West Was Won)", "Led Zeppelin", NOW());
INSERT INTO shows (id, name, date) VALUES (14, 'February 20', '2012-02-20');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (14, "Baba O’Riley (from Houston, TX 1975)", "The Who", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (14, "Factory (from Winterland)", "Bruce Springsteen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (14, "My Hometown (Reggae version from The Green Parrot, Neptune, NJ)", "Bruce Springsteen w/ Jah Love", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (14, "Burning Sky ", "Bad Company", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (14, "My Baby Don’t Tolerate (from Austin City Limits)", "Lyle Lovett &amp; John Hiatt", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (14, "Love Rears Its Ugly Head (Live at Jo Soares, Brazilian talk show, 2007)", "Living Colour", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (14, "Green Grass And High Tides (from Hittin’ The Road Live album, 1993)", "The Outlaws", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (14, "Baba O’Riley", "Dropkick Murphy’s", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (14, "Whiskey in the Jar (from Buy Us A Pint Ya Tight Git album)", "Patrick's Head", NOW());
INSERT INTO shows (id, name, date) VALUES (15, 'February 13', '2012-02-13');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "Beast of Burden (1978 Fort Worth, Texas)", "Rolling Stones", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "Beast of Burden (Keep On Giving: Live Acoustic album)", "Los Lonely Boys", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "How Sweet It Is (Montreaux Jazz Festival 1980)", "Marvin Gaye", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "How Sweet It Is (James Taylor Live album)", "James Taylor", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "Ice Cream Man (1983 San Bernardino, CA)", "Van Halen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "Ice Cream Man (Live Wide Open album)", "Martin Sexton", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "Fortunate Son (Live at MSG)", "Pearl Jam", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "Fortunate Son (from Like A Rock)", "Bob Seger", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "Blowin’ in the Wind (Live at Budokan)", "Bob Dylan", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (15, "Blowin’ in the Wind", "Stevie Wonder", NOW());
INSERT INTO shows (id, name, date) VALUES (16, 'January 30', '2012-01-30');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "Little Red Rooster (1961)", "The Rolling Stones", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "I Am A Man Of Constant Sorrow", "Alison Kraus &amp; Union Station", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "Take Me For Longing", "Allison Krauss &amp; Union Station", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "Omaha (Triple Play Summer Tour, 2007)", "Counting Crows", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "Roads (from The Honest Hour)", "Assembly of Dust", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "Penguins (from Live in Texas album)", "Lyle Lovett", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "Penguin in Bondage", "Frank Zappa", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "Love is Only a Feeling", "The Darkness", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "I Believe in a Thing Called Love", "The Darkness", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "Good For You (Budokan, 1982)", "Toto", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (16, "Passion Jig/Song for Jeffrey", "Jethro Tull", NOW());
INSERT INTO shows (id, name, date) VALUES (17, 'January 23', '2012-01-23');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (17, "New Kid in Town (From Eagles Live)", "The Eagles", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (17, "It's Hard To Be a Saint in The City (1975-1985 Live album)", "Bruce Springsteen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (17, "Canned Music", "Dan Hicks and The Hot Licks", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (17, "The Golden Voice of Vin Scully (Live in Los Angeles)", "Dan Bern", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (17, "Pearly Queen (Woodstock '94)", "Traffic", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (17, "Pride And Joy (MTV Unplugged)", "SRV", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (17, "St. Stephen (Dick's Picks)", "Grateful Dead", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (17, "Strange Kind of Woman (1973)", "Deep Purple", NOW());
INSERT INTO shows (id, name, date) VALUES (18, 'December 12', '2011-12-12');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (18, "Hey Hey My My (Into the Black) (Ragged Glory Tour 1991)", "Neil Young &amp; Crazy Horse", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (18, "Get a Haircut (Viva Las Vegas live album 1993)", "George Thorogood &amp; The Destroyers", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (18, "Family Picture (Live From The American Ballroom)", "Donna the Buffalo", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (18, "I Wanna Learn a Love Song (Great Stories Live album)", "Harry Chapin", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (18, "Right Away People (Entrain Live: Volume 2)", "Entrain", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (18, "Santa Claus is Coming To Town (11/12/09 Buffalo, NY)", "Bruce Springsteen &amp; The E Street Band", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (18, "Speculator (The Honest Hour live album)", "Assembly of Dust", NOW());
INSERT INTO shows (id, name, date) VALUES (19, 'November 28', '2011-11-28');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (19, "Who's Crying Now (Houston, November, 1981)", "Journey", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (19, "I'm Going Home (from Woodstock Festival, Bethel, NY, 1969)", "Ten Years After", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (19, "Come Together (from Woodstock '94)", "The Neville Brothers", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (19, "Travelin' Man/Beautiful Loser (Live Bullet, 1976)", "Bob Seger &amp; The Silver Bullet Band", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (19, "Diner (from Solo album)", "Martin Sexton", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (19, "Shelter from the Storm (from Hard Rain album, 1976)", "Bob Dylan", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (19, "Knockin' on Heaven's Door (from Bob Dylan at Budokan, 1978)", "Bob Dylan", NOW());
INSERT INTO shows (id, name, date) VALUES (20, 'November 21', '2011-11-21');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (20, "Rock Steady (1991)", "Bad Company", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (20, "Loco Motion (1975)", "Grand Funk Railroad", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (20, "Racing in the Street", "Bruce Springsteen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (20, "Paradise By the C (from Live 1975-1985 album)", "Bruce Springsteen", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (20, "Somewhere in Ohio", "The Jayhawks", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (20, "Wipeout", "The Ventures", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (20, "Red Rain (from Secret World album)", "Peter Gabriel", NOW());
INSERT INTO shows (id, name, date) VALUES (21, 'November 14', '2011-11-14');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (21, "Guitar Solo/For A Thousand Mothers", "Jethro Tull", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (21, "Kissing Willie", "Jethro Tull", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (21, "That's The Way", "Led Zeppelin", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (21, "Jean Genie", "David Bowie", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (21, "Billie Jean", "Coldplay", NOW());
INSERT INTO shows (id, name, date) VALUES (22, 'November 7', '2011-11-07');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (22, "Manic Depression", "Seal &amp; Jeff Beck", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (22, "Black Friday", "Steely Dan", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (22, "Gypsy Woman", "Martin Sexton", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (22, "No Smoke Without Fire", "Bad Company", NOW());
INSERT INTO shows (id, name, date) VALUES (23, 'October 17', '2011-10-17');
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (23, "So Much To Say (Live at Piedmont Park)", "Dave Matthews Band", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (23, "Heartbreaker (1974)", "Grand Funk Railroad", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (23, "Old Dan Tucker (Live in Dublin)", "Bruce Springsteen &amp; The Seeger Sessions Band", NOW());
INSERT INTO track_listings (show_id, title, artist, date_added) VALUES (23, "The River of Dreams (1993)", "Billy Joel", NOW());
